### ISSUE TITLE
Does not work with non-default realm instance

### ISSUE THREAD

**Issue by jombie** [bearjaw/RBSRealmBrowser#2]
Does not work for non-default realm instance since the realm passed in instantiation is never used.

**Comment by bearjaw** [comment]
Hi, 
thanks for reporting. I'll fix that asap.

Cheers

**Comment by bearjaw** [comment]
Should be fixed on both branches (master & swift-4). Please run ```pod repo update``` and then ```pod install``` to get the latest changes or delete your pods folder & clear your cocoapods cache.

**Comment by jombie** [comment]
Still not working since during fetch in `resultsForObjectSchemaAtIndex(_ index: Int)` also default realm is used.

**Comment by bearjaw** [comment]
I think I got them all now. Please try again. and remember to run ```pod repo update``` and then ```pod install``` to get the latest changes or delete your pods folder & clear your cocoapods cache.

**Comment by jombie** [comment]
Thanks,
It works now.

Request: One feature enhancement to view detail value of a any given column if it does not fit in a single line like maybe show it in a popup.

**Comment by bearjaw** [comment]
Sounds great. You can open a new issue and I'll tend to it as soon as I can.
